name: publish to action artifact

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    name: Build on windows
    runs-on: windows-latest
    strategy:
      matrix:
          rid: [win-x64, linux-x64, linux-musl-x64, osx-x64]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --verbosity normal
    - name: Build
      run: dotnet publish -c "Release" --self-contained -r "${{ matrix.rid }}" -p:DebugType=None -p:DebugSymbols=false
    - name: Upload program
      uses: actions/upload-artifact@v3
      with:
        name: MD2DocxAvalon-${{ matrix.rid }}
        path: bin/Release/net6.0/${{ matrix.rid }}/publish
    - name: Upload example
      uses: actions/upload-artifact@v3
      with:
        name: example
        path: example