name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            release: bin/Release/net5.0
          - os: windows-latest
            release: bin/Release/net5.0

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: MD2DocxAvalon-${{ matrix.os }}
        path: bin/Release/net5.0