name: .NET

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build on windows
    runs-on: windows-latest
    strategy:
      matrix:
          rid: [win-x64, linux-x64, linux-musl-x64, osx-x64]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --verbosity normal